export const CANDY_MACHINE_ID = process.env.NEXT_PUBLIC_CANDY_MACHINE_ID;
export const CREATOR_WALLET_ADDRESS =
	process.env.NEXT_PUBLIC_CREATOR_WALLET_ADDRESS;
export const COLLECTION_NFT_ADDRESS =
	process.env.NEXT_PUBLIC_COLLECTION_NFT_ADDRESS;
